### ISSUE TITLE
extract pdf to json

### ISSUE THREAD

**Issue by gsgalezowski** [o19s/pdf-discovery-demo#20]
I would like to ask for help in performing the conversion of pdf files to json files. I am running docker and Apache Tika. I run pwsh extract-directory.ps1 ./files5 (here are my pdf files) ./docs_for_solr4.
When executing the script I get the message: "New-Object: /home/grzegorz/pdf-discovery-demo/ocr/extract.ps1:47 $nsmgr = New-object System.XML.XmlNamespaceManager($tika_content.Name .... Constructor not found. Could not find an appropriate constructor for type System.XML.XmlNamespaceManager.InvalidOperation: /home/grzegorz/pdf-discovery-demo/ocr/extract.ps1:48
$nsmgr.AddNamespace('x','http://www.w3.org/1999/xhtml')
Unable to call a method on an expression with a null value. InvalidOperation: /home/grzegorz/pdf-discovery-demo/ocr/ectract.ps1:50
$pages = tika_content.SelectNodes("//x:div[@class='page'],$nsmgr)
Unable to call a method on an expression with a null value.
Done with extraction"
I don't know how to get files that can be used in Solr

**Comment by epugh** [comment]
Did running the basic `docker-compose up --build` work for you?   Also, i think the deploy8ed Tika might have been down..  I just redeployed it and try again!

**Comment by epugh** [comment]
Yeah, pretty sure the problem you had was because the deployed tika was down ;-(.    Going to close this, but please reopen if you don't have success!
